set number
syntax on
set tabstop=4
set showcmd
set wildmenu
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set foldmethod=indent
noremap <S-p> :set relativenumber!
noremap <Enter> i<Enter><Esc>
noremap <Backspace> i<Backspace><Esc>l
