set number
syntax on
set tabstop=4
set showcmd
set wildmenu
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set foldmethod=indent
map  :set nowrap!
map  :set relativenumber!
map  il
map  i
map  :let @/ = ""
map  i
